### ISSUE TITLE
Problem in running the project 

### ISSUE THREAD

**Issue by ChandanAVMYSURU** [MicrosoftTranslator/CSharp-WPF-Example#1]
Warning : Unable to find code signing certificate in the current user’s Windows certificate store. To correct this, either disable signing of the ClickOnce manifest or install the certificate into the certificate store.	WPFExample

**Comment by cpoulain** [comment]
Commit 38e3e6b2c0d3d9d53de7942d9b247e4e527e26e5 should have fixed it.
